name: Build DEV Docker Image

on:
  pull_request:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set lower case repo
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      #      - name: Prettify code
      #        uses: creyD/prettier_action@v4.3
      #        with:
      #          prettier_options: --write **/*.{ts,js,tsx,jsx}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --pull -t ${{ env.REGISTRY }}/${{ REPO_LC }}-dev:latest .
          docker push ${{ env.REGISTRY }}/${{ REPO_LC }}-dev:latest