name: Run DEV CI/CD

on:
  pull_request:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set lower case repo
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      #      - name: Prettify code
      #        uses: creyD/prettier_action@v4.3
      #        with:
      #          prettier_options: --write **/*.{ts,js,tsx,jsx}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --pull -t ${{ env.REGISTRY }}/${{ env.REPO_LC }}-dev:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REPO_LC }}-dev:latest
  eslint-and-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npx --yes eslint .

      - name: Run TypeScript Type Check
        run: |
          npx --yes tsc --noEmit
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier Check
        run: |
          npx --yes prettier --config .prettierrc --check "./src/**/*.{tsx,jsx,ts,js}"